/**
 * dsh-composer-markdown — zero-dependency test runner (node tests/run-tests.mjs).
 *
 * Four suites:
 *   0. bundle freshness — client.js must match the src/client/ sources
 *      byte-for-byte (it is generated by scripts/build.mjs);
 *   1. pure-logic unit tests — client.js is evaluated with a stubbed
 *      window.__ModuleLoader__; the captured factory is invoked with a stub
 *      require and its __internals surface is asserted (no browser needed);
 *   2. bundle shape — parse check plus structural assertions;
 *   3. host contract smoke — grep assertions against the DSH checkout
 *      (opt-in via DSH_CHECKOUT=<path>; skipped when unset or missing).
 *
 * Exit code 0 = all green.
 */

import { readFileSync, existsSync } from 'node:fs'
import { join, resolve } from 'node:path'

const root = resolve(new URL('..', import.meta.url).pathname)
const clientSource = readFileSync(join(root, 'client.js'), 'utf8')

// ── tiny harness ─────────────────────────────────────────────────────────

let passed = 0
let failed = 0
const failures = []

/**
 * One assertion.
 * @param {boolean} condition - the claim.
 * @param {string} label - what the claim is about.
 */
function ok(condition, label) {
  if (condition) {
    passed += 1
  } else {
    failed += 1
    failures.push(label)
    console.error(`  ✗ ${label}`)
  }
}

/**
 * Deep-equal for plan/span shapes (order-sensitive arrays).
 * @param {unknown} actual - produced value.
 * @param {unknown} expected - wanted value.
 * @param {string} label - claim label.
 */
function eq(actual, expected, label) {
  const a = JSON.stringify(actual)
  const b = JSON.stringify(expected)
  ok(a === b, `${label} (got ${a}, want ${b})`)
}

// ── 0. bundle freshness ──────────────────────────────────────────────────

console.log('· bundle freshness')
// client.js is generated from the src/client/ modules; the committed
// artifact must never drift from its sources.
const { renderBundle } = await import('../scripts/build.mjs')
ok(clientSource === renderBundle(),
  'client.js matches the src/client/ sources (run node scripts/build.mjs after editing)')

// ── capture the factory from the bundle ──────────────────────────────────

/** @type {{id: string, factory: Function} | null} */
let registration = null
const stubWindow = {
  __ModuleLoader__: {
    load(record) {
      registration = record
    },
  },
}
// Parse + evaluate the bundle body with the stub window in scope.
const evaluate = new Function('window', clientSource)
evaluate(stubWindow)

ok(registration !== null, 'bundle registers through window.__ModuleLoader__.load')
ok(registration?.id === 'dsh-composer-markdown', 'registration id is the package name')

const plugin = registration?.factory?.(() => ({}))
ok(plugin !== null && typeof plugin === 'object', 'factory returns an exports object')
ok(plugin?.name === 'composer-markdown', 'exports.name matches the cordis entry id')
ok(typeof plugin?.apply === 'function', 'exports.apply is a function')
const I = plugin?.__internals
ok(I !== null && typeof I === 'object', '__internals surface for tests')

// ── 1. pure logic ────────────────────────────────────────────────────────

if (I) {
  console.log('· computeFenceIntervals')
  eq(I.computeFenceIntervals(['hello', 'world']), [], 'no markers → no intervals')
  eq(I.computeFenceIntervals(['```', 'x', '```']), [{ open: 0, close: 2 }], 'basic pair')
  eq(I.computeFenceIntervals(['```ts', 'a', '```', 'text', '```js']),
    [{ open: 0, close: 2 }, { open: 4, close: Infinity }], 'second fence unclosed → Infinity')
  eq(I.computeFenceIntervals(['   ```', 'x', '   ```']), [{ open: 0, close: 2 }], '≤3-space indent markers count')
  eq(I.computeFenceIntervals(['a``` b', '`````']), [{ open: 1, close: Infinity }], 'marker must start the line')
  eq(I.computeFenceIntervals(['`````']), [{ open: 0, close: Infinity }], 'lone long marker line is a marker')
  eq(I.computeFenceIntervals(['a``` b']), [], 'mid-line backticks are not markers')

  console.log('· fenceCoversLine (committed coverage)')
  {
    const iv = I.computeFenceIntervals(['```', 'a', '```', 'b', '```z'])
    eq(iv, [{ open: 0, close: 2 }, { open: 4, close: Infinity }],
      'fixture: one closed pair + one uncommitted marker')
    ok(I.fenceCoversLine(iv, 0) && I.fenceCoversLine(iv, 1) && I.fenceCoversLine(iv, 2),
      'a CLOSED interval covers open, body and close lines')
    eq(I.fenceCoversLine(iv, 3), false, 'the line after a closed fence is outside')
    ok(I.fenceCoversLine(iv, 4), 'an UNCOMMITTED interval covers its own marker line')
    eq(I.fenceCoversLine(iv, 5), false,
      'an UNCOMMITTED interval never covers the lines below (no swallow)')
    eq(I.fenceCoversLine([], 0), false, 'no intervals → nothing covered')
  }

  console.log('· computeInlineCodeSpans')
  eq(I.computeInlineCodeSpans('`foo`'), [{ start: 1, end: 4 }], 'single pair covers inner text')
  eq(I.computeInlineCodeSpans('a `b` c `d` e'), [{ start: 3, end: 4 }, { start: 9, end: 10 }], 'two pairs, left-to-right')
  eq(I.computeInlineCodeSpans('`x'), [], 'odd count: trailing unpaired affects nothing')
  eq(I.computeInlineCodeSpans('``'), [], 'empty pair is skipped (R3 wants non-empty)')
  eq(I.computeInlineCodeSpans('no ticks'), [], 'plain text')
  eq(I.computeInlineCodeSpans('``x``'), [], 'naive pairing: double-backtick delimiters yield empty pairs (v1 rule)')
  eq(I.computeInlineCodeSpans('`a b`'), [{ start: 1, end: 4 }], 'interior spaces are fine — only the inner EDGES must be non-blank')
  eq(I.computeInlineCodeSpans('` x`'), [], 'space right after the opening backtick → no span')
  eq(I.computeInlineCodeSpans('`x `'), [], 'space right before the closing backtick → no span')
  eq(I.computeInlineCodeSpans('` x` y `z`'), [{ start: 8, end: 9 }], 'a blank-edge pair is inert; a later valid pair still renders')
  eq(I.computeInlineCodeSpans('a `b\nc` d'), [], 'a pair may not cross lines (soft newline inside the block)')
  eq(I.computeInlineCodeSpans('`x`\n`y`'), [{ start: 1, end: 2 }, { start: 5, end: 6 }], 'same-line pairs on both sides of a soft break each render')
  eq(I.computeInlineCodeSpans('`\u00a0x`'), [], 'NBSP right inside the delimiter → no span')
  eq(I.computeInlineCodeSpans('`\u3000x`'), [], 'ideographic space (CJK IME) right inside → no span')
  eq(I.computeInlineCodeSpans('`a`b`c`'), [{ start: 1, end: 2 }, { start: 5, end: 6 }], 'adjacent pairs chain left-to-right')

  console.log('· planCodeSpansForBlocks')
  eq(I.planCodeSpansForBlocks(['```', 'code line', '```']),
    [[], [], []], 'fenced lines carry no inline spans — the DOM fence pass styles the block (R5)')
  eq(I.planCodeSpansForBlocks(['```', 'has `x` inside', '```']),
    [[], [], []], 'fence wins over inline pairing (E10); stale bits get cleared by convergence')
  eq(I.planCodeSpansForBlocks(['```', 'unclosed']),
    [[], []], 'uncommitted marker line carries no spans (ticks are markers-in-waiting)')
  eq(I.planCodeSpansForBlocks(['```', 'a `k` b']),
    [[], [{ start: 3, end: 4 }]],
    'uncommitted fence swallows nothing: the plain line below pairs inline code normally')
  eq(I.planCodeSpansForBlocks(['`a` and `b`']),
    [[{ start: 1, end: 2 }, { start: 9, end: 10 }]], 'inline pairing outside fences')
  eq(I.planCodeSpansForBlocks(['a `b\nc` d']),
    [[]], 'cross-line pair inside one (soft-lined) block → no span')

  console.log('· computeCodeDelims / planCodeDelimsForBlocks')
  eq(I.computeCodeDelims('`foo`'), [0, 4], 'single pair: both ticks are delimiters')
  eq(I.computeCodeDelims('say `a` and `b` now'), [4, 6, 12, 14], 'two pairs mark four ticks')
  eq(I.computeCodeDelims('`x'), [], 'unpaired tick is not a delimiter (stays visible)')
  eq(I.computeCodeDelims('``'), [], 'invalid (empty) pair: neither tick is hidden')
  eq(I.computeCodeDelims('` x`'), [], 'invalid (blank-edge) pair: neither tick is hidden')
  eq(I.computeCodeDelims('`a`b`c`'), [0, 2, 4, 6], 'adjacent pairs chain left-to-right')
  eq(I.computeCodeDelims('plain'), [], 'no ticks → no delimiters')
  eq(I.planCodeDelimsForBlocks(['```', 'has `x` inside', '```']),
    [[], [], []], 'fenced backticks are markers, not inline delimiters')
  eq(I.planCodeDelimsForBlocks(['note `k`', 'plain']),
    [[5, 7], []], 'per-block delimiter positions outside fences')
  eq(I.planCodeDelimsForBlocks(['```', 'a `k` b']),
    [[], [2, 4]],
    'uncommitted fence: delimiters pair normally on the plain lines below')

  console.log('· shouldRevealCodeDelims')
  // Canonical span: 'code `k` tail' → content [6, 7), open tick at 5, close tick at 7.
  const span = { start: 6, end: 7 };
  eq(I.shouldRevealCodeDelims(span, 8, 8), false,
    'collapsed caret right after the closing tick → hidden (hides the instant the pair closes)')
  eq(I.shouldRevealCodeDelims(span, 7, 7), false,
    'collapsed caret just inside the closing tick → hidden')
  eq(I.shouldRevealCodeDelims(span, 6, 6), false,
    'collapsed caret at the content head → hidden (caret inside the span)')
  eq(I.shouldRevealCodeDelims(span, 5, 5), false,
    'collapsed caret right before the opening tick → hidden')
  eq(I.shouldRevealCodeDelims(span, 0, 0), false,
    'collapsed caret elsewhere in the block → hidden')
  eq(I.shouldRevealCodeDelims(span, 6, 7), false,
    'range selection strictly inside the content → hidden')
  eq(I.shouldRevealCodeDelims(span, 8, 10), false,
    'range selection adjacent past the closing tick → hidden')
  eq(I.shouldRevealCodeDelims(span, 3, 5), false,
    'range selection adjacent before the opening tick → hidden')
  eq(I.shouldRevealCodeDelims(span, 4, 6), true,
    'selection covering the opening tick → revealed (select-what-you-see)')
  eq(I.shouldRevealCodeDelims(span, 7, 9), true,
    'selection covering the closing tick → revealed')
  eq(I.shouldRevealCodeDelims(span, 0, 12), true,
    'selection spanning the whole pair → revealed')

  console.log('· fenceLangOf')
  eq(I.fenceLangOf('```'), null, 'bare marker → no language')
  eq(I.fenceLangOf('```py'), 'py', 'language id extracted')
  eq(I.fenceLangOf('```c++'), 'c++', 'ids may carry + # . -')
  eq(I.fenceLangOf('```rust '), 'rust', 'trailing space trimmed')
  eq(I.fenceLangOf('  ```ts'), 'ts', 'leading indent tolerated')
  eq(I.fenceLangOf('``` js hello'), null, 'info string with spaces is not an open line')

  console.log('· planFenceDom')
  eq(I.planFenceDom(['```py', 'x = 1', '```']),
    [{ role: 'open', lang: 'py' }, { role: 'body', lang: null }, { role: 'close', lang: null }],
    'closed fence: open/body/close roles, lang on the banner line')
  eq(I.planFenceDom(['```', 'a']),
    [{ role: null, lang: null }, { role: null, lang: null }],
    'uncommitted fence renders plain — no roles until the close exists')
  eq(I.planFenceDom(['plain', '```ts', 'a', 'b', '```', 'tail']),
    [{ role: null, lang: null }, { role: 'open', lang: 'ts' }, { role: 'body', lang: null }, { role: 'body', lang: null }, { role: 'close', lang: null }, { role: null, lang: null }],
    'multi-line body + untouched outside lines')
  eq(I.planFenceDom(['no fences here']),
    [{ role: null, lang: null }], 'no markers → no roles')
  eq(I.planFenceDom(['```']),
    [{ role: null, lang: null }],
    'deferred activation: marker typed, no newline yet → plain text (no box on keystroke)')
  eq(I.planFenceDom(['```py']),
    [{ role: null, lang: null }],
    'deferred activation: language typed, still uncommitted → plain text')
  eq(I.planFenceDom(['a', '```', 'b']),
    [{ role: null, lang: null }, { role: null, lang: null }, { role: null, lang: null }],
    'marker mid-draft never swallows the lines below (commit = Shift+Enter or a close marker)')
  eq(I.planFenceDom(['```', '']),
    [{ role: null, lang: null }, { role: null, lang: null }],
    'empty line below the marker stays plain until the fence commits')
  eq(I.planFenceDom(['```line2', 'x']),
    [{ role: null, lang: null }, { role: null, lang: null }],
    '``` typed at a content line head (dirty open): plain, the tail is not a badge')

  console.log('· planSoftLineSplits')
  {
    const splits = I.planSoftLineSplits
    eq(splits(['hello', 'world']), [[], []], 'no fences → no promotion')
    eq(splits(['hello\n```']), [[6]],
      'soft ``` after a Shift+Enter line is promoted (any-line fix: the marker becomes its own paragraph)')
    eq(splits(['hello\n```ts']), [[6]],
      'soft marker with language id promoted even while deferred (still the last line)')
    eq(splits(['x\n```ts\nfoo()\n```']), [[2, 8, 14]],
      'whole pasted block in one paragraph: open, body, and close each isolated')
    eq(splits(['```\ncode\n```\ntail']), [[4, 9, 13]],
      'text after a close marker on a soft line is split away (close styling would hide it)')
    eq(splits(['a\nb', '```', 'c']), [[], [], []],
      'soft lines outside any fence keep their soft representation')
    eq(splits(['hello', '```ts', 'foo']), [[], [], []],
      'paragraph-headed fence lines: nothing to promote')
    eq(splits(['a\n```ts\nb\nc']), [[2, 8]],
      'uncommitted fence: only marker-adjacent boundaries promote; plain interior lines stay soft')
    eq(splits(['```\n\nx']), [[4]],
      'the empty soft line after the marker promotes away from it; the plain tail stays soft')
    eq(splits(['text\n```line2']), [[5]],
      'a dirty marker head (``` typed at a line head) promotes so the commit gesture can reach it')
    eq(splits(['hi ``` x\n```']), [[9]],
      'backticks mid-line are not markers; only line-head ``` promotes')
    eq(splits(['x\n```', '```']), [[2], []],
      'close marker already heading a paragraph: only the open side promotes')
    eq(splits(['']), [[]], 'empty draft: nothing to do')
  }

  console.log('· isBareCloseMarker')
  ok(I.isBareCloseMarker('```'), 'bare close marker')
  ok(I.isBareCloseMarker('  ```'), 'leading indent still bare')
  eq(I.isBareCloseMarker('```py'), false, 'lang on a close line: not bare')
  eq(I.isBareCloseMarker('``` tail'), false, 'trailing text: not bare')
  eq(I.isBareCloseMarker('``'), false, 'two backticks: not a marker')

  console.log('· planOrphanCleanup')
  {
    const prev = [{ openKey: 'a', closeKey: 'c' }]
    const cur = (list) => list.map(([key, text]) => ({ key, text }))
    eq(I.planOrphanCleanup(prev, prev, cur([['a', '```'], ['b', 'x'], ['c', '```']]), []),
      { removeKeys: [], reselectKey: null, keepPairs: prev },
      'intact pair: nothing removed, still tracked')
    eq(I.planOrphanCleanup(prev, [], cur([['a', ''], ['b', 'x'], ['c', '```']]), ['a']),
      { removeKeys: ['c', 'a'], reselectKey: 'b', keepPairs: [] },
      'opener emptied (user deleted the ```): close + empty line follow; caret hops to the code line')
    eq(I.planOrphanCleanup(prev, [], cur([['b', 'x'], ['c', '```']]), ['b']),
      { removeKeys: ['c'], reselectKey: null, keepPairs: [] },
      'opener paragraph gone: only the orphan close is removed')
    eq(I.planOrphanCleanup(prev, [], cur([['a', '``'], ['b', 'x'], ['c', '```']]), ['a']),
      { removeKeys: [], reselectKey: null, keepPairs: prev },
      'mid-edit opener (partial backticks): keep watching, never delete')
    eq(I.planOrphanCleanup(prev, [], cur([['a', ''], ['b', 'x'], ['c', '``` py']]), []),
      { removeKeys: [], reselectKey: null, keepPairs: [] },
      'close edited by the user: tracking dropped, no removal')
    eq(I.planOrphanCleanup(prev, [{ openKey: 'z', closeKey: 'c' }], cur([['a', ''], ['z', '```js'], ['c', '```']]), []),
      { removeKeys: [], reselectKey: null, keepPairs: [{ openKey: 'z', closeKey: 'c' }] },
      'old close re-paired with a new open: untouchable')
    eq(I.planOrphanCleanup([], [], cur([['k', '```']]), []),
      { removeKeys: [], reselectKey: null, keepPairs: [] },
      'no pair history (user just typing a trailing ```): never removed')
  }

  console.log('· planFenceKey')
  {
    const fence = ['```py', 'a', 'b', '```']
    const tail = ['intro', ...fence, 'outro']
    eq(I.planFenceKey(tail, { index: 2, atStart: true, atEnd: false }, 'Backspace'),
      { kind: 'fence-unwrap', open: 1, close: 4, caret: 2 },
      'Backspace at the first content line start → unwrap: markers die, content survives')
    eq(I.planFenceKey(tail, { index: 5, atStart: true, atEnd: false }, 'Backspace'),
      { kind: 'fence-unwrap', open: 1, close: 4, caret: 5 },
      'Backspace at the paragraph after the box → unwrap')
    eq(I.planFenceKey(tail, { index: 0, atStart: false, atEnd: true }, 'Delete'),
      { kind: 'fence-unwrap', open: 1, close: 4, caret: 0 },
      'Delete at the end of the paragraph before the box → unwrap')
    eq(I.planFenceKey(tail, { index: 3, atStart: false, atEnd: true }, 'Delete'),
      { kind: 'fence-unwrap', open: 1, close: 4, caret: 3 },
      'Delete at the last content line end → unwrap')
    eq(I.planFenceKey(['intro', '```', '```', 'tail'], { index: 1, atStart: false, atEnd: true }, 'Delete'),
      { kind: 'fence-unwrap', open: 1, close: 2, caret: 1 },
      'Delete on an EMPTY fence (close-1 === open, the marker itself) → unwrap (applier homes the caret)')
    eq(I.planFenceKey(tail, { index: 2, atStart: false, atEnd: false }, 'Backspace'),
      null, 'Backspace mid-line: native (content editing)')
    eq(I.planFenceKey(tail, null, 'Backspace'), null, 'range selection / no caret: native')
    eq(I.planFenceKey(tail, { index: 3, atStart: false, atEnd: false }, 'Delete'),
      null, 'Delete mid-line: native')
    eq(I.planFenceKey(['```py', 'a'], { index: 1, atStart: true, atEnd: false }, 'Backspace'),
      null,
      'uncommitted fence is plain text: never atomic (commit or close it first)')
    eq(I.planFenceKey(tail, { index: 2, atStart: true, atEnd: false }, 'ArrowUp'),
      { kind: 'fence-skip-up', open: 1 },
      'ArrowUp at the first content line start → skip over the marker')
    eq(I.planFenceKey(tail, { index: 3, atStart: false, atEnd: true }, 'ArrowDown'),
      { kind: 'fence-skip-down', close: 4 },
      'ArrowDown at the last content line end → skip over the marker')
    eq(I.planFenceKey(['```py', 'a', '```'], { index: 1, atStart: true, atEnd: false }, 'ArrowUp'),
      { kind: 'fence-skip-up', open: 0 },
      'ArrowUp skips even when the box opens the draft (handler clamps)')
    eq(I.planFenceKey(['hello', '```'], { index: 0, atStart: false, atEnd: true }, 'Delete'),
      null,
      'uncommitted (unclosed) marker is plain text: never atomic')
  }

  console.log('· planListRenumber')
  {
    // v2.6: the planner is STATELESS — one pure call per draft state.
    // Whatever the arrival path (delete, split, merge, paste, undo),
    // every ordered run must read 1..n from its first member.
    const ren = (lines) => I.planListRenumber(lines).edits

    // A continuous run is already at its invariant: no edits (and any
    // settled draft costs nothing — the pass converges).
    eq(ren(['1. one', '2. two']), [], 'continuous run: nothing to rewrite')

    // The canonical request: 1. 2. 3. 4. minus the `2.` line.
    eq(ren(['1. one', '3. three', '4. four']),
      [{ index: 1, start: 0, end: 1, digits: '2' }, { index: 2, start: 0, end: 1, digits: '3' }],
      'deleting a middle line closes the gap below (3.→2., 4.→3.)')
    // Deleting the head reanchors the survivors — runs are ALWAYS 1-based.
    eq(ren(['2. two', '3. three']),
      [{ index: 0, start: 0, end: 1, digits: '1' }, { index: 1, start: 0, end: 1, digits: '2' }],
      'deleting the first line renumbers the survivors from 1')
    // Deleting the LAST line leaves a continuous run: no edits.
    eq(ren(['1. one', '2. two']), [],
      'deleting the last line leaves the survivors untouched')

    // ── v2.6 split: a non-item line inside a run restarts the tail at 1 ──
    // (The Shift+Enter exit on an empty item leaves exactly this shape.)
    eq(ren(['1. one', '2. two', '', '4. three', '5. four']),
      [{ index: 3, start: 0, end: 1, digits: '1' }, { index: 4, start: 0, end: 1, digits: '2' }],
      'a run split by a plain line: the tail restarts at 1 (the empty-item exit flow)')
    // The same shape arriving by paste is normalized identically —
    // state-driven, no gesture or memory needed.
    eq(ren(['1. one', '2. two', 'note', '3. three']),
      [{ index: 3, start: 0, end: 1, digits: '1' }],
      'a pasted split normalizes exactly like a typed one')
    // A bullet line between items is a non-item line for the ordered run.
    eq(ren(['1. one', '- dot', '3. three']),
      [{ index: 2, start: 0, end: 1, digits: '1' }],
      'a bullet between items splits the run: the tail restarts at 1')

    // ── v2.6 merge: two 1-based runs fused by deleting the line between ──
    eq(ren(['1. one', '2. two', '1. three', '2. four']),
      [{ index: 2, start: 0, end: 1, digits: '3' }, { index: 3, start: 0, end: 1, digits: '4' }],
      'merged runs renumber as ONE continuous count (1. 2. + 1. 2. → 1. 2. 3. 4.)')

    // ── v2.6 continuity is unconditional (the deliberate trade) ──
    eq(ren(['5. five', '6. six']),
      [{ index: 0, start: 0, end: 1, digits: '1' }, { index: 1, start: 0, end: 1, digits: '2' }],
      'a run cannot hold a non-1 start: it normalizes to 1-based')
    eq(ren(['1. one', '3. three']),
      [{ index: 1, start: 0, end: 1, digits: '2' }],
      'a cold/pasted gap is normalized with no deletion history at all')
    eq(ren(['1. one', '1. two', '1. three']),
      [{ index: 1, start: 0, end: 1, digits: '2' }, { index: 2, start: 0, end: 1, digits: '3' }],
      'lazy numbering is pulled continuous (duplicates are impossible)')
    eq(ren(['1. one', '5. two']),
      [{ index: 1, start: 0, end: 1, digits: '2' }],
      'a manually edited number snaps back to its run position')

    // Empty items (bare prefixes) are members too.
    eq(ren(['1. one', '3. ']),
      [{ index: 1, start: 0, end: 1, digits: '2' }],
      'an empty item is a member: the gap closes as well')

    // Indented items form their own runs — each normalizes from 1 —
    // but the outer run only SUSPENDS through the nested stretch and
    // resumes its count (v2.7): `1. / ␣␣2. / 3.` → deep→1., three→2.
    eq(ren(['1. one', '  2. deep', '3. three']),
      [{ index: 1, start: 2, end: 3, digits: '1' }, { index: 2, start: 0, end: 1, digits: '2' }],
      'a nested stretch suspends the outer run: it resumes at 2 (v2.7, was: reset to 1)')

    // ── v2.7 nesting: deeper lines are content of the item above ──
    // A deeper BULLET line suspends too — the nested list never
    // interrupts the enclosing ordered run (CommonMark). The `1. c`
    // tail is the discriminator: it resumes at 2 (old code restarted
    // the run at the bullet and left it at 1).
    eq(ren(['1. a', '  - b', '1. c']),
      [{ index: 2, start: 0, end: 1, digits: '2' }],
      'a nested bullet stretch suspends the outer run: the tail resumes at 2')
    // Deeper PLAIN lines are wrapped item text: same suspension.
    eq(ren(['1. a', '  wrapped continuation', '1. c']),
      [{ index: 2, start: 0, end: 1, digits: '2' }],
      'deeper plain text (item continuation) suspends the run as well')
    // Multi-level nesting: each level runs 1..n on its own indent,
    // and every outer level resumes past its nested stretch.
    eq(ren(['1. a', '  1. b', '    1. c', '  3. d', '3. e']),
      [{ index: 3, start: 2, end: 3, digits: '2' }, { index: 4, start: 0, end: 1, digits: '2' }],
      'multi-level nesting: d→2 of its own run, the outer e→2 past two nested stretches')
    // A blank line still ends every run outright.
    eq(ren(['1. a', '  1. b', '', '3. c']),
      [{ index: 3, start: 0, end: 1, digits: '1' }],
      'a blank line still splits: the tail below restarts at 1 (no resume)')
    // A line at the run's OWN level still ends it (bullet/plain there).
    eq(ren(['1. a', '  1. b', '- x', '3. c']),
      [{ index: 3, start: 0, end: 1, digits: '1' }],
      'a same-level bullet ends the run: the tail restarts at 1 (no resume)')
    // A shallower member closes the nested runs and starts its own.
    eq(ren(['  1. a', '    1. b', '2. c']),
      [{ index: 2, start: 0, end: 1, digits: '1' }],
      'a shallower member opens a fresh outer run (c→1)')
    // Pasting a whole settled nested CommonMark doc re-plans to
    // NOTHING — the outer count was never reset (old code rewrote
    // two→1. and three→1. here).
    eq(ren(['1. one', '  1. nested', '  2. nested', '2. two', '  - bullet', '3. three']),
      [],
      'a pasted nested document keeps the outer count 1..3 untouched')
    // Mixed paragraphs + soft lines nest identically (visual lines).
    eq(ren(['1. a', '  1. b\n  2. b2', '1. c']),
      [{ index: 2, start: 0, end: 1, digits: '2' }],
      'paragraph/soft-line nesting: the outer run resumes across blocks')

    // Multi-digit renumbering computes the exact digit ranges.
    eq(ren(['9. nine', '10. ten', '11. eleven']),
      [{ index: 0, start: 0, end: 1, digits: '1' },
        { index: 1, start: 0, end: 2, digits: '2' },
        { index: 2, start: 0, end: 2, digits: '3' }],
      'multi-digit: 10.→2. shortens the digit run (width change; apply shifts the caret)')
    eq(ren(['1. one', '2. two', '3. three', '4. four']),
      [],
      'a settled 1..4 run re-plans to nothing (idempotent)')

    // Fenced lines never join a run.
    eq(ren(['1. one', '2. two', '```', '9. code', '```']),
      [],
      'ordered lines inside a fence are not list members')
    // An UNCOMMITTED marker excludes only itself: the plain lines below
    // it stay ordinary members.
    eq(ren(['```note', '1. one', '2. two']),
      [],
      'a lone uncommitted ``` does not swallow the list below it')

    // ── soft-line lists: items as visual lines of one paragraph ──
    eq(ren(['list:\n1. one\n3. three']),
      [{ index: 0, start: 13, end: 14, digits: '2' }],
      'soft-line list: deleting the middle item renumbers the line below')
    eq(ren(['list:\n1. one\n\n3. three']),
      [{ index: 0, start: 14, end: 15, digits: '1' }],
      'a blank soft line splits the run: the tail restarts at 1 immediately')
    eq(ren(['a\n2. two\n3. three']),
      [{ index: 0, start: 2, end: 3, digits: '1' }, { index: 0, start: 9, end: 10, digits: '2' }],
      'soft-line head delete: survivors renumber from 1')
    // A run may span paragraphs: soft-lined tail + separate item paragraphs.
    eq(ren(['intro\n1. one', '3. three']),
      [{ index: 1, start: 0, end: 1, digits: '2' }],
      'mixed soft/paragraph run: a paragraph boundary is just a line break')
    // Multi-digit members inside ONE block: several edits, exact ranges.
    eq(ren(['x\n9. nine\n10. ten']),
      [{ index: 0, start: 2, end: 3, digits: '1' }, { index: 0, start: 10, end: 12, digits: '2' }],
      'soft-line multi-digit: two edits in one block (applied right-to-left)')
    eq(ren(['1. one\n1. two\n1. three']),
      [{ index: 0, start: 7, end: 8, digits: '2' }, { index: 0, start: 14, end: 15, digits: '3' }],
      'lazy soft-line numbering is pulled continuous too')
    // A fenced paragraph's soft lines carry no members at all.
    eq(ren(['```', '1. a\n2. b', '```']),
      [],
      'soft lines of a fenced block are never members')
  }


  console.log('· visualModelOf')
  {
    const m = I.visualModelOf(['hello', 'a\nb\nc', '```', 'x'])
    eq(m.lines.map((l) => [l.block, l.start, l.end, l.text]), [
      [0, 0, 5, 'hello'],
      [1, 0, 1, 'a'], [1, 2, 3, 'b'], [1, 4, 5, 'c'],
      [2, 0, 3, '```'],
      [3, 0, 1, 'x'],
    ], 'lines carry block index + flat [start, end) span + text')
    eq(m.intervals, [{ open: 4, close: Infinity }],
      'fence intervals computed over the visual lines')
    eq(m.lineIndexAt(1, 4), 3, 'caret maps to its visual line (block 1, offset 4 → line 3)')
    eq(m.lineIndexAt(1, 2), 2, 'offset at a soft boundary belongs to the line starting there')
    eq(m.lineIndexAt(0, 5), 0, 'block end maps to its last line')
    eq(m.lineIndexAt(1, 0), 1, 'block head maps to its first line')
    eq(m.lineIndexAt(9, 0), -1, 'unknown block → -1')
    eq(m.inFence(3), false, 'line before the fence')
    eq(m.inFence(4), true, 'the uncommitted marker line itself is covered')
    eq(m.inFence(5), false, 'uncommitted fence covers ONLY its marker line — no swallow below')
    const closed = I.visualModelOf(['```', 'a `k`', '```', 'tail'])
    eq(closed.intervals, [{ open: 0, close: 2 }], 'closed fixture')
    ok(closed.inFence(0) && closed.inFence(1) && closed.inFence(2),
      'a committed fence covers marker and body lines')
    eq(closed.inFence(3), false, 'the line after a committed fence is outside')
    const soft = I.visualModelOf(['a\n```', '```'])
    eq(soft.inFence(1), true, 'soft marker line pairs with the paragraph close marker')
    eq(soft.inFence(0), false, 'plain soft head line is outside the fence')
    eq(soft.lineIndexAt(0, 2), 1, 'caret on the soft marker line resolves to it')
  }

  console.log('· planListMarkerDelete')
  {
    const md = I.planListMarkerDelete
    eq(md(['1. abc'], { index: 0, offset: 0 }, 'Delete'),
      { index: 0, start: 0, prefix: '1. ' },
      'Delete right before the marker eats it forward as one unit')
    eq(md(['- abc'], { index: 0, offset: 0 }, 'Delete'),
      { index: 0, start: 0, prefix: '- ' },
      'the bullet atom dies whole under forward Delete too')
    eq(md(['  1. abc'], { index: 0, offset: 0 }, 'Delete'),
      { index: 0, start: 0, prefix: '  1. ' },
      'v2.8: the indent is part of the atom — Delete at the line head removes indent+marker')
    eq(md(['    - deep'], { index: 0, offset: 0 }, 'Delete'),
      { index: 0, start: 0, prefix: '    - ' },
      'a nested bullet atom (any indent) deletes whole as well')
    eq(md(['1. '], { index: 0, offset: 0 }, 'Delete'),
      { index: 0, start: 0, prefix: '1. ' },
      'a bare prefix (empty item) deletes whole as well')
    eq(md(['hello\n- item'], { index: 0, offset: 6 }, 'Delete'),
      { index: 0, start: 6, prefix: '- ' },
      'soft-line list atoms are atomic at their flat offset')
    eq(md(['1. abc'], { index: 0, offset: 3 }, 'Backspace'), null,
      'Backspace right after the marker is the LEVEL ladder\'s now (v2.8), not the atomic delete')
    eq(md(['- abc'], { index: 0, offset: 2 }, 'Backspace'), null,
      'bullet Backspace after `- `: also the ladder\'s (top-level unlist)')
    eq(md(['1. abc'], { index: 0, offset: 0 }, 'Backspace'), null,
      'Backspace at the line head: native (joins the previous line)')
    eq(md(['1. abc'], { index: 0, offset: 2 }, 'Delete'), null,
      'Delete inside the marker: native (the caret cannot rest there anyway)')
    eq(md(['1. abc'], { index: 0, offset: 1 }, 'Delete'), null,
      'Delete at offset 1 (atom interior): native')
    eq(md(['1. abc'], { index: 0, offset: 5 }, 'Backspace'), null,
      'caret past the atom end (in content): native per-character delete')
    eq(md(['plain'], { index: 0, offset: 5 }, 'Backspace'), null,
      'non-list line: never ours')
    eq(md(['- abc'], null, 'Delete'), null,
      'unusable caret (selection/blur): never ours')
    eq(md(['```', '1. code', '```'], { index: 1, offset: 0 }, 'Delete'), null,
      'marker-looking line inside a fence is code, not a list')
    eq(md(['note\n```\n- x\n```'], { index: 0, offset: 6 }, 'Delete'), null,
      'soft-line marker inside an unpromoted visual fence: not a list')
  }

  console.log('· planListMarkerHop')
  {
    const hop = I.planListMarkerHop
    eq(hop(['1. abc'], { index: 0, offset: 3 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      '← right after `1. ` hops over the whole marker to the line head')
    eq(hop(['- abc'], { index: 0, offset: 2 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      '← right after `- ` hops over the dash+space')
    eq(hop(['* abc'], { index: 0, offset: 2 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      'the `*` bullet marker hops too')
    eq(hop(['1. abc'], { index: 0, offset: 0 }, 'ArrowRight'),
      { index: 0, offset: 3 },
      '→ at the line head hops clear over `1. ` to the content head')
    eq(hop(['  1. abc'], { index: 0, offset: 5 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      'v2.8: the indent is part of the atom — ← from the content head lands at the LINE head')
    eq(hop(['  1. abc'], { index: 0, offset: 0 }, 'ArrowRight'),
      { index: 0, offset: 5 },
      '→ at the line head hops clear over indent+marker in one stroke')
    eq(hop(['  1. abc'], { index: 0, offset: 1 }, 'ArrowRight'),
      { index: 0, offset: 5 },
      'a caret that landed INSIDE the indent (a click): → exits to the far edge')
    eq(hop(['  1. abc'], { index: 0, offset: 1 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      'inside the indent: ← exits backward — the interior is never walked')
    eq(hop(['12. abc'], { index: 0, offset: 1 }, 'ArrowRight'),
      { index: 0, offset: 4 },
      'a caret INSIDE a multi-digit marker (a click): → exits to the far edge')
    eq(hop(['12. abc'], { index: 0, offset: 2 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      'inside the marker: ← exits backward — the interior is never walked')
    eq(hop(['1. abc'], { index: 0, offset: 0 }, 'ArrowLeft'), null,
      '← at the atom START (the line head): native (into the previous line)')
    eq(hop(['1. abc'], { index: 0, offset: 3 }, 'ArrowRight'), null,
      '→ at the marker END: native (into the content)')
    eq(hop(['1. abc'], { index: 0, offset: 4 }, 'ArrowLeft'), null,
      'caret mid-content: native per-character travel')
    eq(hop(['1. '], { index: 0, offset: 3 }, 'ArrowLeft'),
      { index: 0, offset: 0 },
      'a bare prefix (empty item) hops whole as well')
    eq(hop(['hello\n- item'], { index: 0, offset: 8 }, 'ArrowLeft'),
      { index: 0, offset: 6 },
      'soft-line list markers hop at their flat offsets')
    eq(hop(['intro\n1. a\nplain'], { index: 0, offset: 6 }, 'ArrowRight'),
      { index: 0, offset: 9 },
      'soft-line ordered marker: → hops from the line head over `1. ` to `a`')
    eq(hop(['plain'], { index: 0, offset: 2 }, 'ArrowRight'), null,
      'non-list line: never ours')
    eq(hop(['- abc'], null, 'ArrowLeft'), null,
      'unusable caret (selection/blur): never ours')
    eq(hop(['1. abc'], { index: 0, offset: 3 }, 'Backspace'), null,
      'other keys are not this planner\'s business')
    eq(hop(['```', '1. code', '```'], { index: 1, offset: 3 }, 'ArrowLeft'), null,
      'marker-looking line inside a fence is code, not a list')
    eq(hop(['note\n```\n- x\n```'], { index: 0, offset: 10 }, 'ArrowLeft'), null,
      'soft-line marker inside an unpromoted visual fence: not a list')
  }

  console.log('· planListMarkerCaretHome')
  {
    const home = I.planListMarkerCaretHome
    eq(home(['- abc'], { index: 0, offset: 1 }), { index: 0, offset: 0 },
      'caret between `-` and the space (a ↓/click arrival): homes to the NEAREST edge, the line head')
    eq(home(['1. abc'], { index: 0, offset: 1 }), { index: 0, offset: 0 },
      'between `1` and `.`: nearest edge is the line head')
    eq(home(['1. abc'], { index: 0, offset: 2 }), { index: 0, offset: 3 },
      'between `.` and the space: nearest edge is the content head')
    eq(home(['12. abc'], { index: 0, offset: 1 }), { index: 0, offset: 0 },
      'multi-digit marker, front half: snaps to the start')
    eq(home(['12. abc'], { index: 0, offset: 2 }), { index: 0, offset: 0 },
      'multi-digit marker, dead center: a tie snaps to the start (the ArrowLeft exit)')
    eq(home(['12. abc'], { index: 0, offset: 3 }), { index: 0, offset: 4 },
      'multi-digit marker, back half: snaps to the end')
    eq(home(['1. abc'], { index: 0, offset: 0 }), null,
      'AT the atom start (the line head): a legal rest point — stays')
    eq(home(['1. abc'], { index: 0, offset: 3 }), null,
      'AT the atom end (the content head): a legal rest point — stays')
    eq(home(['1. abc'], { index: 0, offset: 4 }), null,
      'mid-content: never ours')
    eq(home(['plain'], { index: 0, offset: 2 }), null,
      'non-list line: never ours')
    eq(home(['1. abc'], null), null,
      'unusable caret (range selection / blur): never ours')
    eq(home(['  - abc'], { index: 0, offset: 3 }), { index: 0, offset: 4 },
      'v2.8: the indent is inside the atom — back-half interiors home to the content head')
    eq(home(['  - abc'], { index: 0, offset: 1 }), { index: 0, offset: 0 },
      'a caret inside the indent (a ↓/click arrival): homes to the LINE head')
    eq(home(['  - abc'], { index: 0, offset: 2 }), { index: 0, offset: 0 },
      'between the indent and the dash (the v2.7 legal point): now interior → the line head')
    eq(home(['    1. x'], { index: 0, offset: 5 }), { index: 0, offset: 7 },
      'deep nesting: interior of indent+marker homes to the nearest edge')
    eq(home(['intro\n12. b'], { index: 0, offset: 7 }), { index: 0, offset: 6 },
      'soft-line markers home at their flat offsets (front half → the soft line head)')
    eq(home(['intro\n12. b'], { index: 0, offset: 9 }), { index: 0, offset: 10 },
      'soft-line markers home at their flat offsets (back half → the content head)')
    eq(home(['```', '1. code', '```'], { index: 1, offset: 1 }), null,
      'marker-looking line inside a fence is code, not a list')
    eq(home(['note\n```\n1. x\n```'], { index: 0, offset: 7 }), null,
      'soft-line marker inside an unpromoted visual fence: not a list')
  }

  console.log('· planListMarkerStyleForBlocks')
  {
    const style = I.planListMarkerStyleForBlocks
    eq(style(['- a', 'plain', '1. b']),
      [[{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }], [], [{ at: 0, kind: 'num' }]],
      'each list line contributes its marker glyphs; plain lines contribute nothing')
    eq(style(['12. deep']),
      [[{ at: 0, kind: 'num' }, { at: 1, kind: 'num' }]],
      'ordered glyphs are SINGLE-CHAR runs: each digit of `12` is its own entry')
    eq(style(['  * star']),
      [[{ at: 2, kind: 'bullet' }, { at: 3, kind: 'bullet-space' }]],
      'the indent is excluded from the styled run (the dash AND its space style)')
    eq(style(['intro\n- a\n2. b']),
      [[{ at: 6, kind: 'bullet' }, { at: 7, kind: 'bullet-space' }, { at: 10, kind: 'num' }]],
      'soft lines contribute their glyphs at flat offsets of the shared block')
    eq(style(['- ', '1. ']),
      [[{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }], [{ at: 0, kind: 'num' }]],
      'bare prefixes (empty items) style too — the bullet gap included')
    eq(style(['999999999. max']),
      [[{ at: 0, kind: 'num' }, { at: 1, kind: 'num' }, { at: 2, kind: 'num' },
        { at: 3, kind: 'num' }, { at: 4, kind: 'num' }, { at: 5, kind: 'num' },
        { at: 6, kind: 'num' }, { at: 7, kind: 'num' }, { at: 8, kind: 'num' }]],
      'a 9-digit marker styles every digit')
    eq(style(['- one']), [[{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }]],
      'v2.4: the bullet atom is TWO glyphs — the dash plus its trailing space (one "• " unit)')
    eq(style(['* two']), [[{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }]],
      'the star bullet gap joins the unit too')
    eq(style(['- three four']), [[{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }]],
      'content spaces are NOT part of the unit — only the marker\'s own space styles')
    eq(style(['```', '- x', '1. y', '```']),
      [[], [], [], []],
      'fenced marker-looking lines are code: no styling')
    eq(style(['```note', '- x']),
      [[], [{ at: 0, kind: 'bullet' }, { at: 1, kind: 'bullet-space' }]],
      'an uncommitted fence covers only its own line: the plain line below styles')
    eq(style(['-x', '1.x', '    - deep', '10. t']),
      [[], [], [{ at: 4, kind: 'bullet' }, { at: 5, kind: 'bullet-space' }],
        [{ at: 0, kind: 'num' }, { at: 1, kind: 'num' }]],
      'non-markers (no space) never style; v2.8 nests at any indent, so a deep bullet styles too')
    eq(style(['plain']), [[]], 'no markers → empty plan')
  }

  console.log('· selectionCoversRange (shared reveal rule)')
  {
    const covers = I.selectionCoversRange
    eq(covers(5, 6, 5, 5), false, 'collapsed caret covers nothing')
    eq(covers(5, 6, 6, 6), false, 'collapsed caret past the run covers nothing')
    eq(covers(5, 6, 5, 6), true, 'range exactly over a 1-char run covers it')
    eq(covers(5, 6, 4, 6), true, 'range ending at the run\'s end covers it')
    eq(covers(5, 6, 6, 8), false, 'range adjacent past the run covers nothing')
    eq(covers(5, 6, 3, 5), false, 'range adjacent before the run covers nothing')
    eq(covers(5, 8, 6, 7), true, 'range strictly inside a multi-char run covers a char')
    eq(covers(5, 8, 0, 12), true, 'range spanning the whole run covers it')
  }

  console.log('· planListShiftDown')
  {
    const sd = I.planListShiftDown
    // Post-insert states: the caret sits right after the NEW marker line.
    eq(sd(['1. a', '2. ', '2. b', '3. c'], { index: 1, offset: 3 }),
      [{ index: 2, start: 0, end: 1, digits: '3' }, { index: 3, start: 0, end: 1, digits: '4' }],
      'insert after 1.: every member below shifts +1 (2.→3., 3.→4.)')
    eq(sd(['1. a', '2. b', '3. ', '3. c'], { index: 2, offset: 3 }),
      [{ index: 3, start: 0, end: 1, digits: '4' }],
      'insert after the middle 2.: only the members BELOW shift')
    eq(sd(['head:\n1. a\n2. \n2. b\n3. c'], { index: 0, offset: 14 }),
      [{ index: 0, start: 15, end: 16, digits: '3' }, { index: 0, start: 20, end: 21, digits: '4' }],
      'soft-line insert: same-block members shift at their flat offsets')
    eq(sd(['1. a', '2. ', '2. b', 'plain', '9. x'], { index: 1, offset: 3 }),
      [{ index: 2, start: 0, end: 1, digits: '3' }],
      'a plain line stops the run: the far group is untouched')
    eq(sd(['1. a', '2. ', '2. b', '  3. deep'], { index: 1, offset: 3 }),
      [{ index: 2, start: 0, end: 1, digits: '3' }],
      'an indent change stops the run: the nested list keeps its numbers')
    eq(sd(['1. a', '2. ', '5. b'], { index: 1, offset: 3 }),
      [{ index: 2, start: 0, end: 1, digits: '3' }],
      'a manual jump is pulled continuous (5.→3.) per the contract')
    eq(sd(['9. a', '10. ', '10. b', '11. c'], { index: 1, offset: 4 }),
      [{ index: 2, start: 0, end: 2, digits: '11' }, { index: 3, start: 0, end: 2, digits: '12' }],
      'multi-digit members renumber with exact ranges (10.→11., 11.→12.)')
    eq(sd(['1. a', '2. ', '2. b', '```', '1. x', '```'], { index: 1, offset: 3 }),
      [{ index: 2, start: 0, end: 1, digits: '3' }],
      'a fence stops the run: fenced markers are code')
    eq(sd(['1. a', '2. b', '3. '], { index: 2, offset: 3 }),
      [], 'inserting at the END shifts nothing (already sequential)')
    eq(sd(['a', '- ', '- b'], { index: 1, offset: 2 }),
      [], 'bullet continuations never cascade')
    eq(sd(['1. a', '2. ', '3. b', '4. c'], { index: 1, offset: 3 }),
      [], 'an already-continuous tail emits no edits (convergence)')
    eq(sd(['1. a'], null), [], 'unusable caret: nothing to shift')
  }

  console.log('· listItemAtomOf')
  {
    const atom = I.listItemAtomOf
    const pick = (r) => (r === null ? null : {
      v: r.v, indent: r.indent, marker: r.marker, start: r.start, end: r.end,
    })
    eq(pick(atom(['1. abc'], { index: 0, offset: 3 })),
      { v: 0, indent: '', marker: '1. ', start: 0, end: 3 },
      'top-level ordered: the atom is the whole marker, start at the line head')
    eq(pick(atom(['  - abc'], { index: 0, offset: 4 })),
      { v: 0, indent: '  ', marker: '- ', start: 0, end: 4 },
      'v2.8: the indent is INSIDE the atom — start is the line head, end the content head')
    eq(pick(atom(['intro\n    1. x'], { index: 0, offset: 11 })),
      { v: 1, indent: '    ', marker: '1. ', start: 6, end: 13 },
      'a soft-line item at any nesting depth resolves its flat atom span')
    eq(atom(['plain'], { index: 0, offset: 3 }), null,
      'a non-list line carries no atom')
    eq(atom(['1. abc'], null), null,
      'unusable caret: no atom')
    eq(atom(['```', '1. code', '```'], { index: 1, offset: 3 }), null,
      'marker-looking line inside a fence is code, not a list')
  }

  console.log('· parentItemWidthOf (the cap\'s parent context, v2.9)')
  {
    const pw = I.parentItemWidthOf
    eq(pw(['- a', '- b'], 1), 0, 'the sibling above is the parent context (width 0)')
    eq(pw(['- a', '  - b', '    - c'], 2), 2, 'a nested item\'s parent is the item above it')
    eq(pw(['- a', 'plain', '  - c'], 2), 0, 'plain lines of any width are skipped, not parents')
    eq(pw(['- a', '  - b'], 0), null, 'a list\'s first item has no parent above')
    eq(pw(['- a', '', '- b'], 2), null, 'a blank ends the block: no parent across it')
    eq(pw(['- a', '```', 'x', '```', '- b'], 4), null, 'a fence region ends the block: no parent across it')
    eq(pw(['h:\n- a\n- b'], 2), 0, 'a plain head line above the list does not end the block')
    eq(pw(['1. a', '  - b'], 1), 0, 'bullet/ordered mix: any item line is a parent context')
  }

  console.log('· planListLevelShift (the level ladder, v2.8; sink capped v2.9)')
  {
    const lv = I.planListLevelShift
    // deeper: the item AND its whole subtree gain one level; a sibling stops.
    eq(lv(['- a', '- b', '  - b1', '    - b2', '- c'], { index: 1, offset: 3 }, 'deeper'),
      { kind: 'indent',
        edits: [
          { index: 1, at: 0, remove: 0, insert: '  ' },
          { index: 2, at: 0, remove: 0, insert: '  ' },
          { index: 3, at: 0, remove: 0, insert: '  ' },
        ], caret: { index: 1, offset: 5 } },
      'Tab: item + nested subtree each +2 (sinks under the sibling above); `- c` is untouched')
    eq(lv(['1. a', '2. b'], { index: 1, offset: 5 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 1, at: 0, remove: 0, insert: '  ' }], caret: { index: 1, offset: 7 } },
      'a plain sibling sink: `2. b` nests under `1. a` (parent 0, self 0)')
    eq(lv(['- a', '      wrapped', '- c'], { index: 2, offset: 3 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 2, at: 0, remove: 0, insert: '  ' }], caret: { index: 2, offset: 5 } },
      'deeper PLAIN lines above are skipped by the parent walk: `- c` still sinks under `- a`')
    eq(lv(['h:\n- a\n- b'], { index: 0, offset: 9 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 0, at: 7, remove: 0, insert: '  ' }], caret: { index: 0, offset: 11 } },
      'soft-line items: the second line sinks at its flat line start (caret 9 → 11)')
    eq(lv(['- a', '- b'], { index: 1, offset: 0 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 1, at: 0, remove: 0, insert: '  ' }], caret: { index: 1, offset: 0 } },
      'caret at the line head rides nothing: it stays the line head')
    eq(lv(['- a', '- b'], { index: 1, offset: 2 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 1, at: 0, remove: 0, insert: '  ' }], caret: { index: 1, offset: 4 } },
      'the caret may sit anywhere on the item line — content head Tab works the same')
    // the v2.9 cap: one level below the parent at most — claimed, but a no-op.
    eq(lv(['- a'], { index: 0, offset: 3 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 0, offset: 3 } },
      'a list\'s FIRST item cannot sink: no parent above to nest under')
    eq(lv(['- a', '  - b'], { index: 1, offset: 5 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 1, offset: 5 } },
      'an item already one level below its parent is AT the cap: no deeper')
    eq(lv(['- a', '  - b', '    - c'], { index: 2, offset: 7 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 2, offset: 7 } },
      'deeper stacks are capped the same (c already one below b)')
    eq(lv(['- a', '      - b'], { index: 1, offset: 9 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 1, offset: 9 } },
      'a hand-typed over-indented item (6 > parent 0) may not sink further')
    eq(lv(['- a', '', '- b'], { index: 2, offset: 3 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 2, offset: 3 } },
      'a blank ends the parent walk: the item after it has nothing to nest under')
    eq(lv(['- a', '```', 'x', '```', '- b'], { index: 4, offset: 3 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 4, offset: 3 } },
      'a fence region ends the parent walk: no parent across it')
    eq(lv(['h:\n1. a\n  2. b'], { index: 0, offset: 6 }, 'deeper'),
      { kind: 'noop', edits: [], caret: { index: 0, offset: 6 } },
      'a plain head line is not a parent: the first list line under it cannot sink')
    // shallower: one level up, subtree riding; odd indents floor at 0.
    eq(lv(['- a', '  - b', '    - c', '- d'], { index: 1, offset: 5 }, 'shallower'),
      { kind: 'dedent',
        edits: [
          { index: 1, at: 0, remove: 2, insert: '' },
          { index: 2, at: 0, remove: 2, insert: '' },
        ], caret: { index: 1, offset: 3 } },
      'Shift+Tab on a nested item: it and its subtree shed one level; siblings stop')
    eq(lv([' 1. a', '   - b'], { index: 0, offset: 5 }, 'shallower'),
      { kind: 'dedent',
        edits: [
          { index: 0, at: 0, remove: 1, insert: '' },
          { index: 1, at: 0, remove: 2, insert: '' },
        ], caret: { index: 0, offset: 4 } },
      'odd (hand-typed) indents: the item loses min(2, own width), deeper lines −2')
    eq(lv(['  - '], { index: 0, offset: 4 }, 'shallower'),
      { kind: 'dedent',
        edits: [{ index: 0, at: 0, remove: 2, insert: '' }], caret: { index: 0, offset: 2 } },
      'a bare nested prefix dedents too (empty item, caret at its end)')
    // top-level shallower: UNLIST — the atom dies, content stays, subtree rises.
    eq(lv(['- a', '  - b', '    - c'], { index: 0, offset: 2 }, 'shallower'),
      { kind: 'unlist',
        edits: [
          { index: 0, at: 0, remove: 2, insert: '' },
          { index: 1, at: 0, remove: 2, insert: '' },
          { index: 2, at: 0, remove: 2, insert: '' },
        ], caret: { index: 0, offset: 0 } },
      'top-level unlist: the marker dies, content stays plain; children still rise')
    eq(lv(['1. one', '2. two', '3. three'], { index: 1, offset: 3 }, 'shallower'),
      { kind: 'unlist',
        edits: [{ index: 1, at: 0, remove: 3, insert: '' }], caret: { index: 1, offset: 0 } },
      'a mid-list unlist leaves the plain line behind (the tail restarts at 1 via renumber)')
    // boundaries: blank and fence lines stop the subtree walk.
    eq(lv(['- a', '- b', '', '  - c'], { index: 1, offset: 3 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 1, at: 0, remove: 0, insert: '  ' }], caret: { index: 1, offset: 5 } },
      'a blank line ends the subtree (the run-semantics boundary)')
    eq(lv(['- a', '- b', '  ```', '  code', '  ```', '  - c'], { index: 1, offset: 3 }, 'deeper'),
      { kind: 'indent',
        edits: [{ index: 1, at: 0, remove: 0, insert: '  ' }], caret: { index: 1, offset: 5 } },
      'a fence region ends the subtree: fenced bytes never shift')
    // guards.
    eq(lv(['plain'], { index: 0, offset: 3 }, 'deeper'), null,
      'a plain line: never ours (Tab keeps its native behavior)')
    eq(lv(['```', '1. code', '```'], { index: 1, offset: 3 }, 'deeper'), null,
      'an item-looking line inside a fence is code, never a list')
    eq(lv(['1. abc'], null, 'deeper'), null,
      'unusable caret (range selection / blur): never ours')
  }

  console.log('· applyLevelEdits (stub nodes)')
  {
    const apply = I.applyLevelEdits
    // Same stub discipline as applyDigitRenames above.
    const makeText = (key, text) => ({
      key,
      __text: text,
      getTextContent() { return this.__text },
      getKey() { return this.key },
      spliceText(offset, delCount, newText) {
        this.__text = this.__text.slice(0, offset) + newText + this.__text.slice(offset + delCount)
        return this
      },
    })
    const makePara = (kids) => ({ getChildren: () => kids })
    const makePoint = (key, offset) => ({
      key, offset, type: 'text',
      set(k, o, t) { this.key = k; this.offset = o; this.type = t },
    })
    const makeEditor = (anchor, focus) => ({
      getEditorState: () => ({ _selection: { anchor, focus } }),
    })
    const asBlocks = (para) => [{ node: para, leaves: [], text: '' }]

    // Indent insert at a block head; the live caret rides the splice.
    {
      const n = makeText('t1', '- a')
      const sel = makePoint('t1', 3)
      apply(makeEditor(sel, sel), asBlocks(makePara([n])),
        { kind: 'indent',
          edits: [{ index: 0, at: 0, remove: 0, insert: '  ' }], caret: { index: 0, offset: 5 } })
      ok(n.__text === '  - a', `indent splice writes two spaces at the head (got ${JSON.stringify(n.__text)})`)
      ok(sel.offset === 5, `the live point rides the insertion (got ${sel.offset})`)
    }
    // Dedent removal spanning fragmented leaves (isolated glyph husks).
    {
      const a = makeText('t1', '  ')
      const b = makeText('t2', '-')
      const c = makeText('t3', ' x')
      const sel = makePoint('t3', 2)
      apply(makeEditor(sel, sel), asBlocks(makePara([a, b, c])),
        { kind: 'dedent',
          edits: [{ index: 0, at: 0, remove: 2, insert: '' }], caret: { index: 0, offset: 2 } })
      ok(a.__text === '' && b.__text === '-' && c.__text === ' x',
        `removal splices the leaf that carries the span (got ${JSON.stringify([a.__text, b.__text, c.__text])})`)
      ok(sel.offset === 2,
        `a point on another leaf keeps its local offset (the removal is elsewhere; got ${sel.offset})`)
    }
    // Soft-line subtree: several edits in one block, applied right-to-left.
    {
      const n = makeText('t1', 'h:\n1. a\n  2. b')
      const sel = makePoint('t1', 6)
      apply(makeEditor(sel, sel), asBlocks(makePara([n])),
        { kind: 'indent',
          edits: [
            { index: 0, at: 3, remove: 0, insert: '  ' },
            { index: 0, at: 8, remove: 0, insert: '  ' },
          ], caret: { index: 0, offset: 8 } })
      ok(n.__text === 'h:\n  1. a\n    2. b',
        `both soft lines of the block shift (got ${JSON.stringify(n.__text)})`)
      ok(sel.offset === 8, `the live point shifts past both insertions (got ${sel.offset})`)
    }
    // Unlist of a bare marker empties the block → the pristine reset.
    {
      const n = makeText('t1', '1. ')
      const para = makePara([n])
      const removed = []
      n.remove = () => removed.push(n.key)
      para.selectStart = () => { para.selected = true }
      apply(makeEditor(undefined, undefined), asBlocks(para),
        { kind: 'unlist',
          edits: [{ index: 0, at: 0, remove: 3, insert: '' }], caret: { index: 0, offset: 0 } })
      ok(n.__text === '', `the bare marker is spliced away (got ${JSON.stringify(n.__text)})`)
      ok(removed.includes('t1') && para.selected === true,
        'an emptied block strips its husk leaves and element-selects (the consumeFlatRange reset)')
    }
    // No selection at all (blurred editor): edits still apply.
    {
      const n = makeText('t1', '- a')
      apply(makeEditor(undefined, undefined), asBlocks(makePara([n])),
        { kind: 'indent',
          edits: [{ index: 0, at: 0, remove: 0, insert: '  ' }], caret: { index: 0, offset: 5 } })
      ok(n.__text === '  - a', 'works with no live selection')
    }
  }

  console.log('· applyDigitRenames (stub nodes)')
  {
    const apply = I.applyDigitRenames
    // Minimal lexical-shaped stubs: text nodes carry __text and splice in
    // place; paragraphs flatten through getChildren (see makeBlock).
    const makeText = (key, text) => ({
      key,
      __text: text,
      getTextContent() { return this.__text },
      getKey() { return this.key },
      spliceText(offset, delCount, newText) {
        this.__text = this.__text.slice(0, offset) + newText + this.__text.slice(offset + delCount)
        return this
      },
    })
    const makeChip = (key, text) => ({
      key,
      __type: 'reference-chip',
      getTextContent() { return text },
      getKey() { return this.key },
    })
    const makePara = (kids) => ({ getChildren: () => kids })
    const makePoint = (key, offset) => ({
      key,
      offset,
      type: 'text',
      set(k, o, t) { this.key = k; this.offset = o; this.type = t },
    })
    const makeEditor = (anchor, focus) => ({
      getEditorState: () => ({ _selection: { anchor, focus } }),
    })

    // Same-width rewrite: text and caret offsets stay put.
    {
      const n = makeText('t1', '3. three')
      const sel = makePoint('t1', 7)
      apply(makeEditor(sel, sel), [{ node: makePara([n]), leaves: [], text: '' }],
        [{ index: 0, start: 0, end: 1, digits: '2' }])
      ok(n.__text === '2. three', `same-width digit rewrite (got ${n.__text})`)
      ok(sel.offset === 7, `same-width: caret offset untouched (got ${sel.offset})`)
    }
    // Width-changing rewrite: the caret slides with the delta.
    {
      const n = makeText('t1', '10. ten')
      const after = makePoint('t1', 6)
      const inside = makePoint('t1', 1)
      const before = makePoint('t1', 0)
      apply(makeEditor(after, inside), [{ node: makePara([n]), leaves: [], text: '' }],
        [{ index: 0, start: 0, end: 2, digits: '9' }])
      ok(n.__text === '9. ten', `width-changing rewrite 10.→9. (got ${n.__text})`)
      ok(after.offset === 5, `caret after the digits shifts by the delta (got ${after.offset})`)
      ok(inside.offset === 1, `caret inside the digits lands at the insertion end (got ${inside.offset})`)
      ok(before.offset === 0, `caret at the start stays (got ${before.offset})`)
    }
    // Digits split across two nodes: the first takes the replacement.
    {
      const a = makeText('ta', '1')
      const b = makeText('tb', '0. ten')
      const sel = makePoint('tb', 5)
      apply(makeEditor(sel, sel), [{ node: makePara([a, b]), leaves: [], text: '' }],
        [{ index: 0, start: 0, end: 2, digits: '9' }])
      ok(a.__text === '9' && b.__text === '. ten',
        `split digit run rewrites across nodes (got ${JSON.stringify([a.__text, b.__text])})`)
      ok(sel.offset === 4, `caret in the second node slides over its lost char (got ${sel.offset})`)
    }
    // A chip inside the digit range aborts that edit, corrupting nothing.
    {
      const chip = makeChip('c1', '9')
      const n = makeText('t1', '. nine')
      apply(makeEditor(null, null), [{ node: makePara([chip, n]), leaves: [], text: '' }],
        [{ index: 0, start: 0, end: 1, digits: '8' }])
      ok(chip.getTextContent() === '9' && n.__text === '. nine',
        'non-text leaf inside the digits: edit skipped safely')
    }
    // Indented prefix: the digit range starts after the indent.
    {
      const n = makeText('t1', '  4. four')
      apply(makeEditor(null, null), [{ node: makePara([n]), leaves: [], text: '' }],
        [{ index: 0, start: 2, end: 3, digits: '2' }])
      ok(n.__text === '  2. four', `indent preserved, digits replaced in place (got ${n.__text})`)
    }
    // No selection at all (blurred editor): still rewrites.
    {
      const n = makeText('t1', '3. three')
      apply(makeEditor(undefined, undefined), [{ node: makePara([n]), leaves: [], text: '' }],
        [{ index: 0, start: 0, end: 1, digits: '2' }])
      ok(n.__text === '2. three', 'works with no live selection')
    }
  }

  console.log('· flatOffsetForKey + selectionCoveredRanges (stub nodes)')
  {
    const fof = I.flatOffsetForKey
    const sc = I.selectionCoveredRanges
    // Lexical-shaped stubs: paragraphs flatten through getChildren
    // (see makeBlock); blockIndexForKey walks getParent up to 'root'.
    const root = { getKey: () => 'root' }
    const makeText = (key, text, parent) => ({
      key,
      __text: text,
      getTextContent() { return this.__text },
      getKey() { return this.key },
      getParent() { return parent },
    })
    const makeChip = (key, text, parent) => ({
      key,
      __type: 'reference-chip',
      getTextContent() { return text },
      getKey() { return this.key },
      getParent() { return parent },
    })
    const makeBlockNode = (key, kids) => ({
      key,
      getKey() { return this.key },
      getChildren: () => kids,
      getParent() { return root },
    })
    const makeBlock = (key, kids, leaves) => ({
      node: makeBlockNode(key, kids),
      leaves,
      text: leaves.map((leaf) => leaf.text).join(''),
    })
    const makeEditor = (map, anchor, focus) => ({
      getEditorState: () => ({ _nodeMap: map, _selection: { anchor, focus } }),
    })
    const wire = (block, kids) => {
      const map = new Map()
      map.set(block.node.key, block.node)
      for (const kid of kids) map.set(kid.key, kid)
      return map
    }
    const makePoint = (key, offset) => ({ key, offset, type: 'text' })

    // ── flatOffsetForKey: element selections map to child boundaries ──
    // Block "ab`cd" as three text children; an element point's offset
    // is the child index it sits before.
    const p1kids = [
      makeText('t1', 'ab', null),
      makeText('t2', '`', null),
      makeText('t3', 'cd', null),
    ]
    const p1 = makeBlock('p1', p1kids, p1kids.map((k) => ({ kind: 'text', node: k, text: k.__text })))
    eq(fof(p1, 'p1', 0), 0, 'element selection offset 0 → block start')
    eq(fof(p1, 'p1', 1), 2, 'element selection before child 1 → boundary after "ab" (v2.7)')
    eq(fof(p1, 'p1', 2), 3, 'element selection before child 2 → boundary after the tick')
    eq(fof(p1, 'p1', 3), 5, 'element selection past the last child → block end')
    eq(fof(p1, 't1', 1), 1, 'text endpoint keeps its direct offset')
    // A chip's clipboard text counts toward the boundary sum.
    const chipKid = makeChip('c1', '@ref', null)
    const tailKid = makeText('t9', 'x', null)
    const p2 = makeBlock('p2', [chipKid, tailKid], [
      { kind: 'chip', node: chipKid, text: '@ref' },
      { kind: 'text', node: tailKid, text: 'x' },
    ])
    eq(fof(p2, 'p2', 1), 4, 'element selection before the text child counts the chip\'s text')
    eq(fof(p2, 'p2', 2), 5, 'element selection past the chip+text → block end')

    // ── selectionCoveredRanges: the reveal projection, per block ──
    const threeBlocks = () => {
      const k1 = [makeText('a1', 'ab`cd', null)]
      const k3 = [makeText('a3', 'ef`gh', null)]
      const k5 = [makeText('a5', 'ij', null)]
      const b1 = makeBlock('p1', k1, k1.map((k) => ({ kind: 'text', node: k, text: k.__text })))
      const b3 = makeBlock('p3', k3, k3.map((k) => ({ kind: 'text', node: k, text: k.__text })))
      const b5 = makeBlock('p5', k5, k5.map((k) => ({ kind: 'text', node: k, text: k.__text })))
      const blocks = [b1, b3, b5]
      const map = new Map()
      blocks.forEach((b) => {
        map.set(b.node.key, b.node)
        for (const kid of b.node.getChildren()) {
          map.set(kid.key, kid)
          kid.getParent = () => b.node
        }
      })
      return { blocks, map }
    }

    // Same block, partial range: the span between the endpoints.
    {
      const { blocks, map } = threeBlocks()
      eq(sc(makeEditor(map, makePoint('a1', 1), makePoint('a1', 4)), blocks),
        [{ index: 0, lo: 1, hi: 4 }],
        'same-block selection → one span between the endpoints')
      eq(sc(makeEditor(map, makePoint('a1', 3), makePoint('a1', 3)), blocks),
        [{ index: 0, lo: 3, hi: 3 }],
        'collapsed caret → empty span (covers nothing, glyphs stay hidden)')
    }
    // Cross-block, anchor above focus: the anchor block keeps its span
    // to the block end, middle blocks are fully covered, the focus
    // block is covered down to its endpoint (v2.7).
    {
      const { blocks, map } = threeBlocks()
      eq(sc(makeEditor(map, makePoint('a1', 1), makePoint('a5', 1)), blocks),
        [{ index: 0, lo: 1, hi: 5 }, { index: 1, lo: 0, hi: 5 }, { index: 2, lo: 0, hi: 1 }],
        'cross-block anchor→focus: per-block projection (upper tail, full middle, lower head)')
    }
    // Reversed (focus above anchor): mirrored halves.
    {
      const { blocks, map } = threeBlocks()
      eq(sc(makeEditor(map, makePoint('a5', 2), makePoint('a1', 5)), blocks),
        [{ index: 0, lo: 5, hi: 5 }, { index: 1, lo: 0, hi: 5 }, { index: 2, lo: 0, hi: 2 }],
        'reversed selection: the same blocks covered, mirrored')
    }
    // Element-selection endpoints ride the boundary mapping too.
    {
      const { blocks, map } = threeBlocks()
      eq(sc(makeEditor(map, { key: 'p1', offset: 1, type: 'element' }, makePoint('a5', 2)), blocks),
        [{ index: 0, lo: 5, hi: 5 }, { index: 1, lo: 0, hi: 5 }, { index: 2, lo: 0, hi: 2 }],
        'element endpoint (before the last child = block end) projects per block')
    }
    // Unresolvable keys: null, nothing reveals.
    eq(sc(makeEditor(new Map(), makePoint('nope', 0), makePoint('a1', 1)), threeBlocks().blocks),
      null, 'an unknown endpoint key → null (no reveal)')
  }

  console.log('· planMarkerNudge')
  {
    const nudge = I.planMarkerNudge
    eq(nudge(['intro', '```py', 'a', 'b', '```', 'tail'], { index: 1, atStart: true, atEnd: false }),
      { index: 2, where: 'start' },
      'caret on the open marker → first content line')
    eq(nudge(['intro', '```py', 'a', 'b', '```', 'tail'], { index: 4, atStart: true, atEnd: false }),
      { index: 3, where: 'end' },
      'caret on the close marker → last content line end')
    eq(nudge(['```py', 'a'], { index: 0, atStart: true, atEnd: false }),
      null,
      'uncommitted marker line is plain text: the caret may rest there (the user is typing on it)')
    eq(nudge(['a', '```'], { index: 1, atStart: true, atEnd: false }),
      null,
      'deferred trailing marker is plain text: no nudge')
    eq(nudge(['intro', '```', '```', 'tail'], { index: 1, atStart: true, atEnd: false }),
      { index: 3, where: 'start' },
      'EMPTY fence (no content line): the caret hops OUT after the box — converges instead of bouncing between the markers')
    eq(nudge(['intro', '```', '```', 'tail'], { index: 2, atStart: true, atEnd: false }),
      { index: 3, where: 'start' },
      'empty fence close side: same outside hop, no ping-pong')
    eq(nudge(['intro', '```', '```'], { index: 1, atStart: true, atEnd: false }),
      { index: 0, where: 'start' },
      'empty fence ending the draft hops to the paragraph before it')
    eq(nudge(['plain', 'text'], { index: 1, atStart: false, atEnd: true }), null,
      'plain lines: no nudge')
    eq(nudge(['```', 'a'], null), null, 'no collapsed caret: no nudge')
  }

  console.log('· computeEnterPlan — lists')
  eq(I.computeEnterPlan(['- apple'], 0), { kind: 'list-continue', indent: '', marker: '- ', offset: 7 }, 'R1 bullet continuation')
  eq(I.computeEnterPlan(['  * star'], 0), { kind: 'list-continue', indent: '  ', marker: '* ', offset: 8 }, 'star + indent')
  eq(I.computeEnterPlan(['1. step'], 0), { kind: 'list-continue', indent: '', marker: '2. ', offset: 7 }, 'R2 numbering')
  eq(I.computeEnterPlan(['3. step'], 0), { kind: 'list-continue', indent: '', marker: '4. ', offset: 7 }, 'non-1 start increments')
  eq(I.computeEnterPlan(['10. ten'], 0), { kind: 'list-continue', indent: '', marker: '11. ', offset: 7 }, 'E11 multi-digit')
  eq(I.computeEnterPlan(['999999999. max'], 0), { kind: 'list-continue', indent: '', marker: '1000000000. ', offset: 14 }, '9-digit cap increments')
  eq(I.computeEnterPlan(['- '], 0), { kind: 'list-exit', prefix: '- ' }, 'E2 empty bullet exits')
  eq(I.computeEnterPlan(['1. '], 0), { kind: 'list-exit', prefix: '1. ' }, 'E2 empty ordered exits')
  eq(I.computeEnterPlan(['  - '], 0), { kind: 'list-exit', prefix: '  - ' }, 'E2 keeps indent in prefix')
  eq(I.computeEnterPlan(['-'], 0), null, 'bare dash without space is not a list')
  eq(I.computeEnterPlan(['    - a'], 0),
    { kind: 'list-continue', indent: '    ', marker: '- ', offset: 7 },
    'v2.8: nesting at ANY indent continues with its own indent (was: >3 not a list)')
  eq(I.computeEnterPlan(['-foo'], 0), null, 'no space after marker → not a list')
  eq(I.computeEnterPlan(['/claim token'], 0), null, 'E6 claim lines never match')
  eq(I.computeEnterPlan(['plain text'], 0), null, 'plain line → native Enter (submit)')
  eq(I.computeEnterPlan(['1.x'], 0), null, 'ordered marker needs a space')

  console.log('· computeEnterPlan — lists on soft (non-first) lines')
  eq(I.computeEnterPlan(['hello\n- apple'], 0, 8),
    { kind: 'list-continue-soft', indent: '', marker: '- ', offset: 8 },
    'soft bullet mid-line: split at the caret, tail becomes the new item (any-line fix + v1.12)')
  eq(I.computeEnterPlan(['hello\n  * star'], 0, 11),
    { kind: 'list-continue-soft', indent: '  ', marker: '* ', offset: 11 },
    'soft bullet keeps its indent, splits at the caret')
  eq(I.computeEnterPlan(['intro\n3. step'], 0, 12),
    { kind: 'list-continue-soft', indent: '', marker: '4. ', offset: 12 },
    'soft ordered line increments (n+1), split at the caret')
  eq(I.computeEnterPlan(['intro\n1. abc\nbye'], 0, 11),
    { kind: 'list-continue-soft', indent: '', marker: '2. ', offset: 11 },
    'mid-line caret splits there: `abc`\'s tail moves behind the new marker; the next soft line stays put')
  eq(I.computeEnterPlan(['hello\n- '], 0, 7),
    { kind: 'list-exit-soft', prefix: '- ', offset: 6 },
    'empty soft bullet exits (prefix consumed on its line)')
  eq(I.computeEnterPlan(['1. \nnext'], 0, 3),
    { kind: 'list-exit-soft', prefix: '1. ', offset: 0 },
    'empty ordered line heading a soft-lined block exits softly')
  eq(I.computeEnterPlan(['hello\n- apple'], 0, 0),
    null, 'caret on the first (plain) soft line → native Shift+Enter')
  eq(I.computeEnterPlan(['hello\nplain'], 0, 9),
    null, 'caret on a later plain soft line → native')
  eq(I.computeEnterPlan(['- item\nstill'], 0, 6),
    { kind: 'list-continue-soft', indent: '', marker: '- ', offset: 6 },
    'list line heading a soft-lined paragraph continues softly (was the whole-block match)')
  eq(I.computeEnterPlan(['hello\n```ts\n- nested\n```'], 0, 19),
    null, 'list prefix on a soft line inside a visual fence does NOT continue (R4-ac3)')
  console.log('· computeEnterPlan — mid-line continuation split (v1.12)')
  eq(I.computeEnterPlan(['- apple pie'], 0, 5),
    { kind: 'list-continue', indent: '', marker: '- ', offset: 5 },
    'caret mid-content on a paragraph list line: split at the caret (tail ` pie` moves down)')
  eq(I.computeEnterPlan(['1. step'], 0, 3),
    { kind: 'list-continue', indent: '', marker: '2. ', offset: 3 },
    'caret exactly at the prefix end: split leaves a bare `1. ` head item')
  eq(I.computeEnterPlan(['1. step'], 0, 1),
    { kind: 'list-continue', indent: '', marker: '2. ', offset: 7 },
    'caret INSIDE the marker: classic append-below (no nonsense split)')
  eq(I.computeEnterPlan(['1. step'], 0, 0),
    { kind: 'list-continue', indent: '', marker: '2. ', offset: 7 },
    'caret at line start: classic append-below (current line keeps its bytes)')
  eq(I.computeEnterPlan(['intro\n3. step'], 0, 7),
    { kind: 'list-continue-soft', indent: '', marker: '4. ', offset: 13 },
    'soft line, caret inside the marker: break at the line end (append)')
  eq(I.computeEnterPlan(['- item\nstill'], 0, 6),
    { kind: 'list-continue-soft', indent: '', marker: '- ', offset: 6 },
    'caret at the soft line end: break at the line end (unchanged)')
  eq(I.computeEnterPlan(['hello', '- real'], 1, 8),
    { kind: 'list-continue', indent: '', marker: '- ', offset: 6 },
    'paragraph-headed list (not the draft\'s first block) keeps the paragraph plan')

  console.log('· computeEnterPlan — fences')
  eq(I.computeEnterPlan(['```'], 0), { kind: 'fence-close' }, 'R4 bare fence start closes')
  eq(I.computeEnterPlan(['```ts'], 0), { kind: 'fence-close' }, 'fence start with language (caret past the ticks keeps the lang)')
  eq(I.computeEnterPlan(['```c++'], 0), { kind: 'fence-close' }, 'language ids may carry + # . -')
  eq(I.computeEnterPlan(['```rust '], 0), { kind: 'fence-close' }, 'trailing space tolerated')
  // v2.7: a caret BEFORE the ticks (offset 0) keeps the native soft
  // break — the caret was moved to the line head deliberately, so
  // the commit gesture stays out of the way (the documented contract
  // finally holds for bare marker lines too).
  eq(I.computeEnterPlan(['```'], 0, 0),
    null, 'bare ``` with caret at offset 0: plain text, native break (was: skeleton)')
  eq(I.computeEnterPlan(['   ```'], 0, 0),
    null, 'indented bare marker, caret before the ticks: native break')
  eq(I.computeEnterPlan(['```'], 0, 1),
    { kind: 'fence-close' }, 'caret inside the ticks of a bare marker: the skeleton still commits')
  eq(I.computeEnterPlan(['```ts'], 0, 0),
    null, '```lang with caret at offset 0: native break (the contract, unchanged)')
  eq(I.computeEnterPlan(['```', 'x'], 1),
    null, 'uncommitted interior is plain text: native break / list grammar below')
  eq(I.computeEnterPlan(['```', '1. x'], 1),
    { kind: 'list-continue', indent: '', marker: '2. ', offset: 4 },
    'list below an uncommitted marker continues normally (nothing swallowed)')
  eq(I.computeEnterPlan(['```', 'code', '```'], 1),
    { kind: 'fence-newline', offset: 4 }, 'inside closed fence at line end: append below (unchanged)')
  eq(I.computeEnterPlan(['```', 'let x = 1', '```'], 1, 5),
    { kind: 'fence-newline', offset: 5 },
    'body line, caret mid-line: break AT THE CARET — the ` = 1` tail moves to the new line')
  eq(I.computeEnterPlan(['```', 'let x = 1', '```'], 1, 0),
    { kind: 'fence-newline', offset: 0 },
    'body line, caret at line start: empty line grows above (textarea semantics)')
  eq(I.computeEnterPlan(['```', 'code', '```'], 2), { kind: 'fence-exit' }, 'on the closing line: break after the block')
  eq(I.computeEnterPlan(['```', 'code', '```'], 0),
    { kind: 'fence-newline', offset: 3 }, 'completed pair open marker: append a body line, never split the marker')
  eq(I.computeEnterPlan(['``` js hello'], 0),
    { kind: 'fence-commit', offset: 3 },
    'marker-ish line with a spaced tail: commit splits at the ticks, tail survives below the close')
  eq(I.computeEnterPlan(['```line2', 'x'], 0, 3),
    { kind: 'fence-commit', offset: 3 },
    '``` just typed at a content line head (caret after the ticks): commit keeps the tail OUT of the box')
  eq(I.computeEnterPlan(['a', '```line2', 'b'], 1, 3),
    { kind: 'fence-commit', offset: 3 },
    'same commit mid-draft: everything after the tick run stays below the box')
  eq(I.computeEnterPlan(['  ```tail'], 0, 5),
    { kind: 'fence-commit', offset: 5 },
    'indent rides the marker run (commit offset = indent + ticks)')
  eq(I.computeEnterPlan(['```ts'], 0, 3),
    { kind: 'fence-commit', offset: 3 },
    'caret still at the tick end on a lang-looking line: content preservation wins (`ts` moves below)')
  eq(I.computeEnterPlan(['```line2'], 0, 0),
    null, 'caret before the ticks (offset 0): plain text, native break')
  eq(I.computeEnterPlan(['- item', '```', '- nested', '```'], 2),
    { kind: 'fence-newline', offset: 8 }, 'R4-ac3: list prefix inside fence does NOT continue the list')
  eq(I.computeEnterPlan(['- item', '```', 'code', '```'], 0), { kind: 'list-continue', indent: '', marker: '- ', offset: 6 }, 'list outside fences still continues')
  eq(I.computeEnterPlan(['```', 'a', '```', '- x'], 3), { kind: 'list-continue', indent: '', marker: '- ', offset: 3 }, 'list after a closed fence continues')
}

// ── 2. bundle shape ──────────────────────────────────────────────────────

console.log('· bundle shape')
// new Function() above already proved the file parses.
ok(clientSource.includes('GENERATED FILE'),
  'generated-artifact banner present (edit src/client/, not client.js)')
ok(clientSource.includes('__dmdFactories') && clientSource.includes("'./index':"),
  'in-bundle module registry concatenates the src/client/ modules')
ok(clientSource.includes("window.__ModuleLoader__.load({"), 'loader wrapper present')
ok(clientSource.includes("id: 'dsh-composer-markdown'"), 'module id is the package name')
ok(clientSource.includes('[data-composer-input]'), 'composer selector present')
ok(clientSource.includes('[data-composer-card] [role="listbox"]'), 'menu probe present')
ok(clientSource.includes('IS_CODE = 1 << 4'), 'IS_CODE bit constant')
ok(clientSource.includes("tag: HISTORY_MERGE_TAG") || clientSource.includes("'history-merge'"), 'history-merge tag used')
ok(clientSource.includes('event.stopImmediatePropagation()'), 'matched Shift+Enter is kept from Lexical')
ok(clientSource.includes('keyCode === IME_KEYCODE'), 'IME keyCode 229 guard')
ok(clientSource.includes('event.repeat') && clientSource.includes('event.defaultPrevented'), 'repeat + yielded-key guards')
ok(clientSource.includes("keys: new Set(['Tab'])")
  && clientSource.includes('return !event.ctrlKey && !event.metaKey && !event.altKey;'),
  'Tab ladder claims held repeats (repeats re-plan; an item line never falls through to focus traversal)')
ok(clientSource.includes('return event.shiftKey')
  && clientSource.includes('!event.ctrlKey && !event.metaKey && !event.altKey'),
  'plain Enter / Ctrl+Cmd+Enter / Alt variants are never intercepted (native submit preserved)')
ok(clientSource.includes('dmd-fence-open') && clientSource.includes('dmd-fence-body') && clientSource.includes('dmd-fence-close'),
  'fence block classes present (whole-region code styling)')
ok(clientSource.includes('font-size: 0px') || clientSource.includes('font-size: 0'),
  'fence markers hidden via zero font size')
ok(clientSource.includes('content: attr(${FENCE_LANG_ATTR})'),
  'language id rendered as a CSS attr() badge (selector composed from the class constants)')
ok(clientSource.includes('editor.getElementByKey'),
  'fence pass reaches paragraph DOM through the editor API')
ok(clientSource.includes('uncommitted fence: plain text'),
  'committed-fence activation: an uncommitted ``` (no closing marker) renders plain — nothing is swallowed mid-draft')
ok(clientSource.includes('fenceCoversLine'),
  'fence coverage is derived once (doc.js) — planners share the committed-coverage rule')
ok(clientSource.includes('line-height: 0px') && clientSource.includes('background: transparent'),
  'opening marker line is zero-height: the box top starts at the first content line (no banner)')
ok(clientSource.includes('position: absolute') && clientSource.includes('content: attr(${FENCE_LANG_ATTR})'),
  'language id is an overlay badge, never a dedicated line')
ok(clientSource.includes('p.${FENCE_CLASS_OPEN}:not([${FENCE_LANG_ATTR}=""]) + p.${FENCE_CLASS_BODY}'),
  'a language id widens the badge band on the first content line')
ok(clientSource.includes('planOrphanCleanup') && clientSource.includes('node.remove()'),
  'deleting a fence opener removes its paired orphan close (scaffold cleanup)')
ok(clientSource.includes('planFenceKey') && clientSource.includes("'fence-unwrap'") && clientSource.includes("'fence-skip-down'"),
  'atomic fence keys: one Backspace/Delete at a boundary UNWRAPS the box (markers die, content survives); arrows skip marker lines')
ok(clientSource.includes("'fence-commit'") && clientSource.includes('commitPlanForOpenLine'),
  'Shift+Enter on an uncommitted ``` line commits the box (tail content split below the close)')
ok(clientSource.includes('planListRenumber') && clientSource.includes('applyDigitRenames'),
  'ordered-list renumber: a deletion inside a numbered list closes the gap')
ok(clientSource.includes('renumberEditsOf') && !clientSource.includes('trackedListRuns'),
  'v2.6 renumber is STATE-DRIVEN: every run reads 1..n from the draft alone (no cross-pass run memory)')
ok(clientSource.includes('const target = String(run.size)') || clientSource.includes("String((run.size += 1))"),
  'the renumber walk assigns each member its 1-based run position')
ok(clientSource.includes('ORDERED_ITEM_RE'),
  'ordered-item grammar groups lists for renumbering')
ok(clientSource.includes('shiftPointOverSplice'),
  'renumber shifts the caret across width-changing digit rewrites')
ok(!/dmd-fence-open\.dmd-raw/.test(clientSource),
  'no raw-reveal rules: the ``` markers are never shown (imperceptible)')
ok(clientSource.includes('dmd-code-delim') && clientSource.includes('CODE_DELIM_CLASS')
  && clientSource.includes('shouldRevealCodeDelims') && !clientSource.includes('owner.end + 1')
  && !clientSource.includes('display: none')
  && clientSource.includes('letter-spacing: -1ch') && clientSource.includes('color: transparent'),
  'inline-code delimiters hide on closure (zero-advance, real caret metrics; never display:none); only a selection covering a tick reveals them')
ok(clientSource.includes('list-continue-soft') && clientSource.includes('list-exit-soft'),
  'soft-line list continuation: `- ` / `1. ` on ANY visual line continues the list')
ok(clientSource.includes("klassOf(editor, 'linebreak')"),
  'soft continuation inserts the host\'s real LineBreakNode (not a literal \\n)')
ok(clientSource.includes('caretBlockPoint'),
  'enter arbitration reads the caret\'s flat offset (visual-line model)')
ok(clientSource.includes('planListMarkerDelete') && clientSource.includes('BULLET_ITEM_RE'),
  'list atoms are atomic: Delete before an atom (indent+marker) removes the whole unit in one stroke')
ok(clientSource.includes('planListMarkerHop') && clientSource.includes("'ArrowLeft'") && clientSource.includes("'ArrowRight'"),
  'atomic markers TRAVEL whole too: plain ←/→ hop over the marker, never through its interior')
ok(clientSource.includes('placeFlatCaret(block.node, plan.offset)'),
  'the hop lands the caret at the planned flat point through the edit algebra')
ok(clientSource.includes('planListMarkerCaretHome') && clientSource.includes('planListMarkerCaretHome(analysis, caretBlockPoint(editor, blocks))'),
  'v2.3 caret-home: a collapsed caret resting inside a marker (↓/↑/click arrivals) homes to the nearest marker edge')
ok(clientSource.includes('function consumeFlatRange(editor, block, start, end)') && clientSource.includes('reset the paragraph to the pristine'),
  'v2.3 dead-composer fix: a marker delete that empties its whole block resets it to the pristine childless shape (no husk leaves, an element selection)')
ok(clientSource.includes('consumeFlatRange(editor, block, plan.start, plan.start + plan.prefix.length)'),
  'every atomic marker erase goes through the reset-aware consumeFlatRange')
ok(clientSource.includes('huskBlocksOf(blocks)') && clientSource.includes('guarded: renumber.length > 0 || husks.length > 0'),
  'the repairs stage sweeps stranded husk blocks back to pristine shape (convergent + loop-guarded)')
ok(clientSource.includes('dmd-list-num') && clientSource.includes('dmd-list-bullet')
  && clientSource.includes('planListMarkerStyleForBlocks'),
  'list markers render distinct from body text: ordered digits + bullet dash get their own styled leaves')
ok(clientSource.includes('[data-composer-input] .${LIST_NUM_CLASS}')
  && clientSource.includes('[data-composer-input] .${LIST_BULLET_CLASS}::after')
  && clientSource.includes('content: "•"'),
  'ordered digits take the code font; the bullet dash renders as a "•" dot AFTER the zero-advance dash (the line-head caret then reads BEFORE the dot, like ordered)')
ok(clientSource.includes("'bullet-space'") && clientSource.includes('[data-composer-input] .${LIST_BULLET_SPACE_CLASS}')
  && clientSource.includes('LIST_BULLET_SPACE_CLASS'),
  'v2.4: the bullet atom\'s trailing space joins the "• " unit — its own leaf class takes the marker code font')
ok(clientSource.includes('selectionCoversRange') && clientSource.includes('applyGlyphMarks'),
  'marker styling shares the reveal rule: only a selection genuinely covering a glyph shows the raw char')
ok(clientSource.includes('shapeMismatch(block,\n          analysis.spans[i],\n          analysis.delims[i],\n          analysis.markers[i].map((g) => g.at),')
  || clientSource.includes('analysis.markers[i].map((g) => g.at)'),
  'the shape stage isolates marker glyph leaves with the same single-char machinery as code delimiters')
ok(clientSource.includes('planListShiftDown'),
  'ordered continuation shifts the run below +1 (insert keeps the list continuous, duplicate-free)')
ok(clientSource.includes('planListLevelShift') && clientSource.includes('applyLevelEdits')
  && clientSource.includes('LEVEL_STEP') && clientSource.includes("'shallower'")
  && clientSource.includes("'deeper'"),
  'v2.8 level ladder: Tab/Shift+Tab/Backspace-at-the-atom lift or sink an item with its whole subtree (one discrete update)')
ok(clientSource.includes('parentItemWidthOf') && clientSource.includes("kind: 'noop'")
  && clientSource.includes("plan.kind === 'noop'"),
  'v2.9 sink cap: an item may sink at most one level below its parent (nearest item above); a capped Tab claims the key but moves nothing')
ok(clientSource.includes('listItemAtomOf') && clientSource.includes('caret.offset === atom.end'),
  'Backspace right after a list atom (indent+marker) is the ladder\'s lift gesture')
ok(clientSource.includes("'unlist'") && clientSource.includes('keys: new Set([\'Tab\'])'),
  'a top-level lift UNLISTS the item (atom dies, content stays) and the Tab gesture owns the ladder')
ok(!clientSource.includes('planListBackspace') && !clientSource.includes('planListReanchor')
  && !clientSource.includes('joinSoftLineAbove') && !clientSource.includes('joinParagraphAbove'),
  'the v1.13 join/detach Backspace is gone — the ladder unlist replaced it (no dead planners bundled)')

// architecture shape (v2.0 refactor): layers + no duplicated derivations
ok(clientSource.includes('visualModelOf') && clientSource.includes('createRestyler') && clientSource.includes('createGestures'),
  'layered architecture: shared document model, engine + key surface as composed instances')
ok(!clientSource.includes("lastIndexOf('\\n'"),
  'the caret visual-line resolution lives once in the document model (no per-planner re-derivation)')
ok(clientSource.includes("require('./edits')") && !clientSource.includes("require('./style-pass')"),
  'all live-node mutations go through the edit algebra module')

const hostEntry = readFileSync(join(root, 'index.js'), 'utf8')
ok(hostEntry.includes('export function apply'), 'host entry exports apply')
ok(hostEntry.includes("export const name = 'composer-markdown'"), 'host entry name')

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
ok(pkg.dsh?.bundle?.patch === './cordis.patch.yml', 'package declares dsh.bundle.patch')
ok(pkg.dsh?.client?.platform === 'web', 'package declares dsh.client platform web')
ok(pkg.exports?.['./client'] === './client.js', 'exports maps ./client to the bundle')
ok(Object.keys(pkg.dependencies ?? {}).length === 0, 'zero runtime dependencies')

// ── 3. host contract smoke (opt-in) ──────────────────────────────────────

console.log('· host contract smoke')
const checkout = process.env.DSH_CHECKOUT
if (checkout === undefined || checkout === '') {
  console.log('  (skipped — set DSH_CHECKOUT=<dsh checkout> to enable)')
} else if (!existsSync(join(checkout, 'packages/client/ui-conversation'))) {
  console.log(`  (skipped — ${checkout} has no packages/client/ui-conversation)`)
  ok(false, `DSH_CHECKOUT points at a DSH checkout (${checkout})`)
} else {
  const read = (path) => readFileSync(join(checkout, path), 'utf8')
  const conv = 'packages/client/ui-conversation/src/client/input'
  const keymap = read(`${conv}/editor/keymap.ts`)
  ok(keymap.includes('KEY_ENTER_COMMAND') && keymap.includes('COMMAND_PRIORITY_CRITICAL'),
    'F7: composer Enter handler still registered at CRITICAL priority')
  ok(keymap.includes('isComposing') && keymap.includes('229'),
    'F11: host IME guards still present (our three signals mirror them)')
  const editable = read(`${conv}/editor/ComposerContentEditable.tsx`)
  ok(editable.includes('data-composer-input'), 'F2a: contenteditable still marked data-composer-input')
  const menu = read('packages/client/ui-input-trigger/src/client/MenuView.tsx')
  ok(menu.includes('role="listbox"'), 'F12: trigger menu still renders role=listbox')

  // Code block visuals we mirror in the composer (tokens + geometry).
  const codeBlock = read('packages/client/ui-primitives/src/markdown/CodeBlock.module.css')
  ok(codeBlock.includes('--dsw-alias-markdown-code-block'), 'R5: code-block background token still exists')
  ok(codeBlock.includes('--dsw-alias-markdown-code-block-banner'), 'R5: banner background token still exists')
  ok(codeBlock.includes('--dsw-font-markdown-code-block'), 'R5: code-block font token still exists')
  ok(/border-radius:\s*12px/.test(codeBlock), 'R5: code-block radius still 12px')

  // Lexical dist: resolve through the dependency range in ui-conversation.
  const convPkg = JSON.parse(read('packages/client/ui-conversation/package.json'))
  const lexicalRange = convPkg.dependencies?.lexical
  ok(typeof lexicalRange === 'string', 'composer still depends on lexical')
  const candidates = lexicalRange?.match(/\d+\.\d+\.\d+/) ?? []
  const version = candidates[0]
  const lexicalPaths = [
    version ? join(checkout, 'node_modules/.pnpm', `lexical@${version}_typescript@6.0.3/node_modules/lexical/dist/Lexical.dev.js`) : '',
    join(checkout, 'node_modules/lexical/dist/Lexical.dev.js'),
  ].filter(Boolean)
  const lexicalPath = lexicalPaths.find((p) => existsSync(p))
  if (lexicalPath === undefined) {
    console.log('  (lexical dev bundle not found in checkout node_modules — skipping lexical assertions)')
  } else {
    const lexical = readFileSync(lexicalPath, 'utf8')
    ok(lexical.includes('__lexicalEditor = editor'), 'F2b: editor still attached on the root element')
    ok(lexical.includes('IS_CODE = 1 << 4'), 'F3: IS_CODE still bit 4')
    ok(lexical.includes("return 'code'"), 'F4: code format still renders a <code> element')
    ok(lexical.includes('getElementByKey'), 'F13: getElementByKey still resolves node → DOM for the fence pass')
  }
}

// ── summary ──────────────────────────────────────────────────────────────

console.log(`\n${passed} passed, ${failed} failed`)
if (failed > 0) {
  console.error(failures.map((f) => `  - ${f}`).join('\n'))
  process.exit(1)
}
